# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

"""language toggle

Revision ID: 0d1e5f390e64
Revises: 9d7fa2e6b24c
Create Date: 2024-09-20 12:55:17.347169

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '0d1e5f390e64'
down_revision = '9d7fa2e6b24c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz", sa.Column("language_toggle", sa.Boolean(), nullable=False,server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz", "language_toggle")
    # ### end Alembic commands ###
